/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Autocomplete, TextField, Box } from '@mui/material';
import { styled } from '@mui/material/styles';
import useCountries from './useCountries';
 
const Property1Default = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `320px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const AutocompleteCountry = styled(Autocomplete)({  
  width: `320px`,  
  margin: `0px`,  
});
 
function Countries(props) {
  const {data, fns} = useCountries();
  return (
    <Property1Default >
       <AutocompleteCountry  onChange = { (e, val) =>
        val ? props.setCountryCode(val.code) : props.setCountryCode("")} options={data.countries}   autoHighlight disableClearable openOnFocus blurOnSelect getOptionLabel={option => option.label || ""} value={props.signupInfo.country ? fns.getCountry(props.signupInfo.country) : null} renderInput={(params) => ( <TextField variant="standard" {...params} fullWidth  label={`Country`}  helperText={props.signupInfo.errors["country"]}  error={Boolean(props.signupInfo.errors["country"])}/> )}  renderOption = { (props, option) => (
          <Box component="li" sx={{ '& > img': { mr: 2, flexShrink: 0 } }} {...props}>
            <img
              loading="lazy"
              width="20"
              src={`https://flagcdn.com/w20/${option.code.toLowerCase()}.png`}
              srcSet={`https://flagcdn.com/w40/${option.code.toLowerCase()}.png 2x`}
              alt=""
            />
            {option.label}
          </Box>
        )}/>
     </Property1Default>
   );
}

export default Countries;
