/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import VectorImage from './assets/images/Vector.png';
import { styled } from '@mui/material/styles';
import useDropdownPlaceholder from './useDropdownPlaceholder';
 
const DropdownPlaceholder1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `173px`,  
  height: `21px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  cursor: `pointer`,  
});
  
const NovaBrazilWorkspace = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(39, 39, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector = styled("img")({  
  height: `5px`,  
  width: `10px`,  
  position: `absolute`,  
  left: `163px`,  
  top: `7px`,  
});
 
function DropdownPlaceholder() {
  const {fns} = useDropdownPlaceholder();
  return (
    <DropdownPlaceholder1 onClick={fns.toggleSelect} >
       <NovaBrazilWorkspace >
         {`Nova Brazil - Workspace`}
           </NovaBrazilWorkspace>
       <Vector  src={VectorImage} alt={"Vector"}/>
     </DropdownPlaceholder1>
   );
}

export default DropdownPlaceholder;
