/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import SwitchDarkImage from './assets/images/switch_dark_2.png';
import SwitchDark1Image from './assets/images/switch_dark_1.png';
import { styled } from '@mui/material/styles';

 
const PricingCode = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const SwitchDark = styled("img", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ props }) =>({  
  height: `58px`,  
  width: `34px`,  
  margin: props.exportMethod === "remote" ? `0px 0px 0px 2px` : `0px`,  
  cursor: `pointer`,  
}));
  
const SwitchDark1 = styled("img", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ props }) =>({  
  height: `58px`,  
  width: `34px`,  
  margin: props.exportMethod === "remote" ? `0px` : `0px 0px 0px 2px`,  
  cursor: `pointer`,  
}));
  
const Text = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 2px`,  
});
  
const Left = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ theme, props }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: theme.typography["Typography"]["Body 2"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 2"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 2"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 2"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 2"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 2"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 2"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 2"].textTransform,  
  margin: `0px`,  
  opacity: props.exportMethod === "remote" ? `0.30000001192092896` : "unset",  
}));
  
const Right = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ theme, props }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: theme.typography["Typography"]["Body 2"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 2"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 2"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 2"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 2"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 2"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 2"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 2"].textTransform,  
  opacity: props.exportMethod === "remote" ? "unset" : `0.30000001192092896`,  
  margin: `-2px 0px 0px 0px`,  
}));
 
function ExportSwitch(props) {
  return (
    <PricingCode >
       {(!(props.exportMethod === "remote")) &&
           <SwitchDark onClick={() => props.onClick('remote')
} props={props}  src={SwitchDarkImage} alt={"switch_dark"}/>
       }
       {((props.exportMethod === "remote")) &&
           <SwitchDark1 onClick={() => props.onClick('local')
} props={props}  src={SwitchDark1Image} alt={"switch_dark"}/>
       }
       <Text >
         <Left props={props} >
           {`Download Code`}
             </Left>
         <Right props={props} >
           {`Push to Repository`}
             </Right>
       </Text>
     </PricingCode>
   );
}

export default ExportSwitch;
