/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const FaqPopUp1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Faq = styled("div")({  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `24px`,  
  boxSizing: `border-box`,  
  width: `320px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const YouWonTBeChargedUnti = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Background"]["Default"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  width: `224px`,  
  margin: `0px`,  
}));
  
const YourTrialBeginsOnFeb = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Background"]["Default"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `16px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `6px 0px 0px 0px`,  
}));
 
function FaqPopUp(props) {
  return (
    <FaqPopUp1 >
       <Faq >
         <YouWonTBeChargedUnti >
           {`You won’t be charged until your free trial ends.`}
             </YouWonTBeChargedUnti>
         <YourTrialBeginsOnFeb >
           {"Your trial begins on " + props.currentDate + " and ends on " + props.chargeDate + ". You can cancel anytime before " +  props.chargeDate + " to avoid being charged by going to the Account Settings > Subscription tab. You will be automatically charged for your subscription on " + props.chargeDate + " if you do not cancel."}
             </YourTrialBeginsOnFeb>
       </Faq>
     </FaqPopUp1>
   );
}

export default FaqPopUp;
