/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Alert } from '@mui/material';
import { styled } from '@mui/material/styles';
import AlertOutlined from './AlertOutlined';
import AlertStandard from './AlertStandard';

 
const Frame121: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `691px`,  
  height: `316px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const AlertFilled: any = styled(Alert)({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `30px`,  
  top: `64px`,  
});
  
const AlertFilled1: any = styled(Alert)({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `30px`,  
  top: `114px`,  
});
  
const AlertFilled2: any = styled(Alert)({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `30px`,  
  top: `164px`,  
});
  
const AlertFilled3: any = styled(Alert)({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `30px`,  
  top: `214px`,  
});
  
const AlertOutlined1: any = styled(AlertOutlined)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `264px`,  
  top: `64px`,  
}));
  
const AlertOutlined2: any = styled(AlertOutlined)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `264px`,  
  top: `114px`,  
}));
  
const AlertOutlined3: any = styled(AlertOutlined)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `264px`,  
  top: `164px`,  
}));
  
const AlertOutlined4: any = styled(AlertOutlined)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `264px`,  
  top: `214px`,  
}));
  
const AlertStandard1: any = styled(AlertStandard)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `498px`,  
  top: `64px`,  
}));
  
const AlertStandard2: any = styled(AlertStandard)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `498px`,  
  top: `114px`,  
}));
  
const AlertStandard3: any = styled(AlertStandard)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `498px`,  
  top: `164px`,  
}));
  
const AlertStandard4: any = styled(AlertStandard)(({ theme }: any) =>({  
  width: `160px`,  
  height: `38px`,  
  position: `absolute`,  
  left: `498px`,  
  top: `214px`,  
}));
 
function Frame12(): JSX.Element {
  return (
    <Frame121 >
       <AlertFilled variant="filled" severity={"error"}   > Description </AlertFilled>
         <AlertFilled1 variant="filled" severity={"warning"}   > Description </AlertFilled1>
         <AlertFilled2 variant="filled" severity={"info"}   > Description </AlertFilled2>
         <AlertFilled3 variant="filled" severity={"success"}   > Description </AlertFilled3>
         <AlertOutlined1   />
       <AlertOutlined2   />
       <AlertOutlined3   />
       <AlertOutlined4   />
       <AlertStandard1   />
       <AlertStandard2   />
       <AlertStandard3   />
       <AlertStandard4   />
     </Frame121>
   );
}

export default Frame12;
