/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';

 
const Frame11: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `538px`,  
  height: `246px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Rectangle1: any = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  width: `158px`,  
  height: `63px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `33px`,  
});
 
function Frame1(): JSX.Element {
  return (
    <Frame11 >
       <Rectangle1 >
       </Rectangle1>
     </Frame11>
   );
}

export default Frame1;
