/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import UpImage from './assets/images/up.png';
import { styled } from '@mui/material/styles';

 
const Property1Big = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `29px 14px`,  
  boxSizing: `border-box`,  
});
  
const Up = styled("img")({  
  height: `185px`,  
  width: `331px`,  
  margin: `0px`,  
});
 
function ImageTest() {
  return (
    <Property1Big >
       <Up  src={UpImage} alt={"up"}/>
     </Property1Big>
   );
}

export default ImageTest;
