/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Badge from './Badge';
import useLoginHeader from './useLoginHeader';
 
const LoginHeader1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `54px`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `0px 20px`,  
  boxSizing: `border-box`,  
});
  
const LogIn = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  textTransform: `none`,  
  cursor: `pointer`,  
}));
 
function LoginHeader() {
  const {fns} = useLoginHeader();
  return (
    <LoginHeader1 >
       <Badge   />
       <LogIn onClick={fns.loginClick} >
         {`Log In`}
           </LogIn>
     </LoginHeader1>
   );
}

export default LoginHeader;
