/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const MultiLinePlacholder1 = styled("div")({  
  backgroundColor: `rgba(233, 233, 233, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `180px`,  
  height: `71px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
});
 
function MultiLinePlacholder() {
  return (
    <MultiLinePlacholder1 >
     </MultiLinePlacholder1>
   );
}

export default MultiLinePlacholder;
