/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import TypeJavascript from './TypeJavascript';
import TypeTypescript from './TypeTypescript';

 
const Property1Default = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `12px 0px 0px 0px`,  
  boxSizing: `border-box`,  
});
  
const TypeJavascript1 = styled(TypeJavascript)(({ theme }) =>({  
  width: `100px`,  
  height: `46px`,  
  margin: `0px`,  
}));
  
const TypeTypescript1 = styled(TypeTypescript)(({ theme }) =>({  
  width: `100px`,  
  height: `46px`,  
  margin: `0px`,  
}));
 
function PickFileType(props) {
  return (
    <Property1Default >
       <TypeJavascript1   selected={props.language === "JavaScript"} onClick={() => {props.onClick("JavaScript")}}/>
       <TypeTypescript1   selected={props.language === "TypeScript"} onClick={() => {props.onClick("TypeScript")}}/>
     </Property1Default>
   );
}

export default PickFileType;
