/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import TypeNextJs from './TypeNextJs';
import TypeCreateReactApp from './TypeCreateReactApp';

 
const PickExportType1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const TypeNextJs1 = styled(TypeNextJs)(({ theme }) =>({  
  width: `118px`,  
  height: `46px`,  
  margin: `0px`,  
}));
  
const TypeCreateReactApp1 = styled(TypeCreateReactApp)(({ theme }) =>({  
  width: `118px`,  
  height: `46px`,  
  margin: `0px`,  
}));
 
function PickExportType(props) {
  return (
    <PickExportType1 >
       <TypeNextJs1   selected={props.framework === "NextJS"} onClick={()=> {props.onClick("NextJS")}}/>
       <TypeCreateReactApp1   selected={props.framework === "CRA"} onClick={() => {props.onClick("CRA")}}/>
     </PickExportType1>
   );
}

export default PickExportType;
