/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import QuestLogoVertical1Image from './assets/images/Quest_Logo_Vertical.png';
import { styled } from '@mui/material/styles';

 
const ModeLight = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const QuestLogoVertical1 = styled("img")({  
  height: `68.14px`,  
  width: `54px`,  
  margin: `0px`,  
});
 
function QuestLogoVertical() {
  return (
    <ModeLight >
       <QuestLogoVertical1  src={QuestLogoVertical1Image} alt={"Quest Logo Vertical"}/>
     </ModeLight>
   );
}

export default QuestLogoVertical;
