/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import Icon1Image from './assets/images/icon_2.png';
import DotImage from './assets/images/dot_6.png';
import Dot1Image from './assets/images/dot_5.png';
import Dot2Image from './assets/images/dot_4.png';
import DividerImage from './assets/images/divider_2.png';
import FigmaIconImage from './assets/images/Figma_Icon_2.png';
import VidIconImage from './assets/images/Vid_Icon_2.png';
import { styled } from '@mui/material/styles';

 
const ReactBannerImage1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Left = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Icon1 = styled("img")({  
  height: `42px`,  
  width: `32.67px`,  
  margin: `0px`,  
});
  
const Text = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Frame27 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Dot = styled("img")({  
  height: `5px`,  
  width: `5px`,  
  margin: `0px`,  
});
  
const DuplicateTheFreeMuiC = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame28 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Dot1 = styled("img")({  
  height: `5px`,  
  width: `5px`,  
  margin: `0px`,  
});
  
const GetTheFullMuiKit = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame29 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Dot2 = styled("img")({  
  height: `5px`,  
  width: `5px`,  
  margin: `0px`,  
});
  
const QuestSampleComponent = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Middle = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Divider = styled("img")({  
  height: `50.55px`,  
  width: `1.72px`,  
  margin: `0px`,  
});
  
const FigmaIcon = styled("img")({  
  height: `43px`,  
  width: `30px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Text1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const GetThe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const QuestPluginForFigma = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Right = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Divider1 = styled("div")({  
  opacity: `0.5`,  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  width: `1.72px`,  
  height: `50.55px`,  
  margin: `0px`,  
});
  
const VidIcon = styled("img")({  
  height: `38px`,  
  width: `58px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Text2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const WatchThe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const IntroVideo = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
 
function ReactBannerImage() {
  return (
    <ReactBannerImage1 >
       <Left >
         <Icon1  src={Icon1Image} alt={"icon"}/>
         <Text >
           <Frame27 >
             <Dot  src={DotImage} alt={"dot"}/>
             <DuplicateTheFreeMuiC >
               {`Duplicate the Free MUI Community Kit`}
                 </DuplicateTheFreeMuiC>
           </Frame27>
           <Frame28 >
             <Dot1  src={Dot1Image} alt={"dot"}/>
             <GetTheFullMuiKit >
               {`Get the Full MUI Kit`}
                 </GetTheFullMuiKit>
           </Frame28>
           <Frame29 >
             <Dot2  src={Dot2Image} alt={"dot"}/>
             <QuestSampleComponent >
               {`Quest Sample Components`}
                 </QuestSampleComponent>
           </Frame29>
         </Text>
       </Left>
       <Middle >
         <Divider  src={DividerImage} alt={"divider"}/>
         <FigmaIcon  src={FigmaIconImage} alt={"Figma Icon"}/>
         <Text1 >
           <GetThe >
             {`Get the`}
               </GetThe>
           <QuestPluginForFigma >
             {`Quest Plugin for Figma`}
               </QuestPluginForFigma>
         </Text1>
       </Middle>
       <Right >
         <Divider1 >
         </Divider1>
         <VidIcon  src={VidIconImage} alt={"Vid Icon"}/>
         <Text2 >
           <WatchThe >
             {`Watch the`}
               </WatchThe>
           <IntroVideo >
             {`Intro Video`}
               </IntroVideo>
         </Text2>
       </Right>
     </ReactBannerImage1>
   );
}

export default ReactBannerImage;
