/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import CalendarImage from './assets/images/Calendar.png';
import DividerImage from './assets/images/divider.png';
import Icon1Image from './assets/images/icon.png';
import BulletImage from './assets/images/bullet_1.png';
import Bullet1Image from './assets/images/bullet.png';
import VidIconImage from './assets/images/Vid_Icon.png';
import { styled } from '@mui/material/styles';
import useReactBanner from './useReactBanner';
 
const ReactBanner1 = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop.toString())
  })(({ props }) =>({  
  background: `linear-gradient(90deg, rgba(107, 104, 255, 1) 6.074792355261352%, rgba(71, 183, 246, 1) 75.31986118918232%)`,  
  borderRadius: `4px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: props.width,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `12px 30px`,  
  boxSizing: `border-box`,  
}));
  
const Left = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Calendar = styled("img")({  
  height: `40px`,  
  width: `36px`,  
  margin: `0px`,  
});
  
const Text = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const BookAFree = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const OnboardingSession = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
  cursor: `pointer`,  
});
  
const Middle = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `358.38px`,  
  margin: `0px 0px 0px 68px`,  
});
  
const Divider = styled("img")({  
  height: `50.55px`,  
  width: `1.72px`,  
  margin: `0px`,  
});
  
const Icon1 = styled("img")({  
  height: `42px`,  
  width: `32.67px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Frame29 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Frame291 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Bullet = styled("img")({  
  height: `4px`,  
  width: `4px`,  
  margin: `0px`,  
});
  
const GetTheFigmaPlugin = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
  cursor: `pointer`,  
});
  
const Frame28 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `2px 0px 0px 0px`,  
});
  
const Bullet1 = styled("img")({  
  height: `4px`,  
  width: `4px`,  
  margin: `0px`,  
});
  
const QuickStartBuildYourF = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
  cursor: `pointer`,  
});
  
const Right = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 68px`,  
});
  
const Divider1 = styled("div")({  
  opacity: `0.5`,  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  width: `1.72px`,  
  height: `50.55px`,  
  margin: `0px`,  
});
  
const VidIcon = styled("img")({  
  height: `38px`,  
  width: `58px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Text1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 30px`,  
});
  
const WatchThe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const IntroVideo = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  lineHeight: `19px`,  
  textTransform: `none`,  
  margin: `0px`,  
  cursor: `pointer`,  
});
 
function ReactBanner(props) {
  const {fns} = useReactBanner();
  return (
    <ReactBanner1 props={props} >
       <Left >
         <Calendar  src={CalendarImage} alt={"Calendar"}/>
         <Text >
           <BookAFree >
             {`Book a free`}
               </BookAFree>
           <OnboardingSession onClick={fns.redirectToScheduleOnboarding} >
             {`Onboarding Session`}
               </OnboardingSession>
         </Text>
       </Left>
       <Middle >
         <Divider  src={DividerImage} alt={"divider"}/>
         <Icon1  src={Icon1Image} alt={"icon"}/>
         <Frame29 >
           <Frame291 >
             <Bullet  src={BulletImage} alt={"bullet"}/>
             <GetTheFigmaPlugin onClick={fns.redirectToFigmaPlugin} >
               {`Get the Figma Plugin`}
                 </GetTheFigmaPlugin>
           </Frame291>
           <Frame28 >
             <Bullet1  src={Bullet1Image} alt={"bullet"}/>
             <QuickStartBuildYourF onClick={fns.redirectToQuickStart} >
               {`Quick Start  - Build your first component`}
                 </QuickStartBuildYourF>
           </Frame28>
         </Frame29>
       </Middle>
       <Right >
         <Divider1 >
         </Divider1>
         <VidIcon  src={VidIconImage} alt={"Vid Icon"}/>
         <Text1 >
           <WatchThe >
             {`Watch the`}
               </WatchThe>
           <IntroVideo onClick={fns.redirectToIntroVideo} >
             {`Intro Video`}
               </IntroVideo>
         </Text1>
       </Right>
     </ReactBanner1>
   );
}

export default ReactBanner;
