/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { TextField, InputAdornment, SvgIcon } from '@mui/material';
import { ReactComponent as RemoveRedEyeFilled1 } from './assets/images/RemoveRedEyeFilled.svg';
import { styled } from '@mui/material/styles';

 
const Tst1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `269px`,  
  height: `92px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const DarkModeFalseSizeSma: any = styled(TextField)({  
  width: `220px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `20px`,  
});
 
function Tst(): JSX.Element {
  return (
    <Tst1 >
       <DarkModeFalseSizeSma variant="filled" size="small"  label={`Label`} helperText="Teste" InputProps={{endAdornment: <InputAdornment position="end"><SvgIcon sx={{width: "24px", height: "24px"}} component = { RemoveRedEyeFilled1 } /></InputAdornment>}}  />
     </Tst1>
   );
}

export default Tst;
