/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useAddWorkspace = () => {
  let data = {};
  const onWorkspaceNameChange = () => {};
  const onWorkspaceNameBlur = () => {};
  const addWs = () => {};
  const addUserToWorkspace = (param1) => {};

  let fns = {onWorkspaceNameChange, onWorkspaceNameBlur, addWs, addUserToWorkspace};
  return {data, fns};
}

export default useAddWorkspace;