/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useAppSettings = () => {
  let data = {};
  const updateField = () => {};
  const onFieldBlur = (param1) => {};
  const closeImportFontDialog = (param1) => {};
  const getCompsToExcludeVal = (param1) => {};
  const updateExportSetting = (param1, param2) => {};
  const handleExportApp = () => {};
  const pushToRemoteBranch = () => {};
  const setCurrentAPIKey = (param1) => {};

  let fns = {updateField, onFieldBlur, closeImportFontDialog, getCompsToExcludeVal, updateExportSetting, handleExportApp, pushToRemoteBranch, setCurrentAPIKey};
  return {data, fns};
}

export default useAppSettings;