/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useAppCard = () => {
  let data = {};
  const handleDotsClick = (param1, param2) => {};

  let fns = {handleDotsClick};
  return {data, fns};
}

export default useAppCard;