/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useAppDetails = () => {
  let data = {};
  const onAppNameChange = () => {};
  const onAppNameBlur = () => {};
  const updateExportSetting = (param1, param2) => {};
  const onDesignSystemNameChange = () => {};
  const onDesignSystemNameBlur = () => {};
  const deleteApp = () => {};
  const handleDeleteFont = (param1, param2) => {};
  const handleImportFont = () => {};
  const handleFiles = () => {};

  let fns = {onAppNameChange, onAppNameBlur, updateExportSetting, onDesignSystemNameChange, onDesignSystemNameBlur, deleteApp, handleDeleteFont, handleImportFont, handleFiles};
  return {data, fns};
}

export default useAppDetails;