/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useDeleteApp = () => {
  let data = {};
  const onDeleteAppBlur = () => {};
  const onDeleteAppChange = () => {};
  const deleteApp = (param1) => {};

  let fns = {onDeleteAppBlur, onDeleteAppChange, deleteApp};
  return {data, fns};
}

export default useDeleteApp;