/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useDowngradeUpgrade = () => {
  let data = {};
  const handleDowngrade = (param1) => {};
  const handleUpgrade = () => {};
  const handleContactSales = (param1) => {};

  let fns = {handleDowngrade, handleUpgrade, handleContactSales};
  return {data, fns};
}

export default useDowngradeUpgrade;