/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useDeleteWorkspace = () => {
  let data = {};
  const deleteWs = (param1) => {};
  const onDeleteWorkspaceBlur = () => {};
  const onDeleteWorkspaceChange = () => {};

  let fns = {deleteWs, onDeleteWorkspaceBlur, onDeleteWorkspaceChange};
  return {data, fns};
}

export default useDeleteWorkspace;