/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useImportFontDialog = () => {
  let data = {};
  const handleImportFont = (param1) => {};
  const onFontFamilyChange = () => {};
  const onFontWeightChange = () => {};
  const onFileNameChange = () => {};

  let fns = {handleImportFont, onFontFamilyChange, onFontWeightChange, onFileNameChange};
  return {data, fns};
}

export default useImportFontDialog;