/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useInviteToWorkspace = () => {
  let data = {};
  const InviteToWorkspace = (param1) => {};
  const inviteMember = () => {};
  const onUsersEmailChange = () => {};
  const onUsersEmailBlur = () => {};

  let fns = {InviteToWorkspace, inviteMember, onUsersEmailChange, onUsersEmailBlur};
  return {data, fns};
}

export default useInviteToWorkspace;