/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useReactBanner = () => {
  let data = {};
  const redirectToSampleComponents = () => {};
  const redirectToFullMUKit = () => {};
  const redirectToFreeMUIKit = () => {};
  const redirectToIntroVideo = () => {};
  const redirectToFigmaPlugin = () => {};
  const redirectToQuickStart = () => {};
  const redirectToScheduleOnboarding = () => {};

  let fns = {redirectToSampleComponents, redirectToFullMUKit, redirectToFreeMUIKit, redirectToIntroVideo, redirectToFigmaPlugin, redirectToQuickStart, redirectToScheduleOnboarding};
  return {data, fns};
}

export default useReactBanner;