/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useRepoApiKey = () => {
  let data = {};
  const validateKey = (param1) => {};
  const onApiKeyBlur = () => {};
  const onApiKeyChange = () => {};
  const onKeyNameBlur = () => {};
  const onKeyNameChange = () => {};

  let fns = {validateKey, onApiKeyBlur, onApiKeyChange, onKeyNameBlur, onKeyNameChange};
  return {data, fns};
}

export default useRepoApiKey;