/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useWorkspaceAppBreadcrumbs = () => {
  let data = {};
  const changeApp = (param1, param2, param3) => {};
  const changeWorkspace = (param1) => {};

  let fns = {changeApp, changeWorkspace};
  return {data, fns};
}

export default useWorkspaceAppBreadcrumbs;