/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import SeparatorImage from './assets/images/Separator_1.png';
import Separator1Image from './assets/images/Separator.png';
import { styled } from '@mui/material/styles';
import DropdownPlaceholder from './DropdownPlaceholder';
import useWorkspaceAppBreadcrumbs from './useWorkspaceAppBreadcrumbs';
 
const WorkspaceAppBreadcru = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Workspace = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ImagePlaceholder = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
  })(({ data }) =>({  
  backgroundImage: `url(${ImagePlaceholderImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  mixBlendMode: `multiply`,  
  width: `21px`,  
  height: `21px`,  
  margin: `0px`,  
  backgroundImage: `url(${data.thumbnail})`,  
}));
  
const DropdownPlaceholder1 = styled(DropdownPlaceholder)(({ theme }) =>({  
  margin: `0px 0px 0px 10px`,  
}));
  
const Separator = styled("img")({  
  height: `9.85px`,  
  width: `6px`,  
  margin: `0px 0px 0px 16px`,  
});
  
const App = styled(DropdownPlaceholder)(({ theme }) =>({  
  margin: `0px 0px 0px 16px`,  
}));
  
const Separator1 = styled("img")({  
  height: `9.85px`,  
  width: `6px`,  
  margin: `0px 0px 0px 16px`,  
});
  
const Components = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(39, 39, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 16px`,  
});
 
function WorkspaceAppBreadcrumbs() {
  const {data, fns} = useWorkspaceAppBreadcrumbs();
  return (
    <WorkspaceAppBreadcru >
       <Workspace >
         <ImagePlaceholder data={data} >
         </ImagePlaceholder>
         <DropdownPlaceholder1   value={data.currentWorkspace?.workspaceId}
          options={data.workspaceOptions}
          onValueChange={fns.changeWorkspace}
          disabled={
            data.processingStatus === "CHANGING WORKSPACE COMPONENTS PAGE" ||
            false
          }/>
       </Workspace>
       <Separator  src={SeparatorImage} alt={"Separator"}/>
       <App           value={data.currentApp?.appId}
        options={data.accountAppOptions}
        onValueChange={fns.changeApp}
        disabled={
          [
            "CHANGING WORKSPACE COMPONENTS PAGE",
            "CHANGING APP COMPONENTS PAGE",
          ].includes(data.processingStatus) || false
        }/>
       <Separator1  src={Separator1Image} alt={"Separator"}/>
       <Components >
         {`Components`}
           </Components>
     </WorkspaceAppBreadcru>
   );
}

export default WorkspaceAppBreadcrumbs;
