/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const QuestDefault: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.05)`,  
  borderRadius: `6px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `42px 30px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Price: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `120.34px`,  
  margin: `0px`,  
});
  
const Q49: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `42px`,  
  letterSpacing: `-0.42px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `uppercase`,  
  margin: `0px`,  
});
  
const Mo: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(161, 161, 161, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `500`,  
  fontSize: `18px`,  
  letterSpacing: `-0.18px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const LoremIpsumPlacementT: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  width: `180px`,  
  margin: `21px 0px 0px 0px`,  
});
  
const ButtonContained: any = styled(Button)({  
  height: `50px`,  
  width: `180px`,  
  margin: `30px 0px 0px 0px`,  
});
 
function Pricing1(): JSX.Element {
  return (
    <QuestDefault >
       <Top >
         <Price >
           <Q49 >
             {`$49`}
               </Q49>
           <Mo >
             {`/mo`}
               </Mo>
         </Price>
         <LoremIpsumPlacementT >
           {`Lorem ipsum placement text to make you click Sign-up.`}
             </LoremIpsumPlacementT>
       </Top>
       <ButtonContained variant="contained" size="large" color="primary"    > Sign-up </ButtonContained>
     </QuestDefault>
   );
}

export default Pricing1;
